easy_admin:
    entities:
        Batch:
            class: 'App\Entity\Batch'
            list:
                fields:
                    - Name
            new:
                fields: ['name', 'type', 'dateAcquired', 'numberOfMales', 'numberOfFemales', 'costPerBird']
        Type:
            class: 'App\Entity\Type'
        Expense:
            class: 'App\Entity\Expense'
            new:
                fields:
                    - {name: date, type: date, property: date}
                    - description
                    - amount
                    - type
                    - category
        Income:
            class: 'App\Entity\Income'
        Category:
            class: 'App\Entity\Category'