easy_admin:
    design:
        brand_color: gold
        menu:
            - { label: 'Home', route: 'home_index'}
            - {label: 'Account', children: ['Expense', 'Income']}
            - { entity: 'Batch', default: true }
            - Category
            - Appuser
            - Farm
            - { label: 'Market', route: 'market_index'}
    site_name: Farm Back End
    entities:
        Batch:
            class: 'App\Entity\Batch'
            list:
                fields:
                    - name
                    - dateAcquired
                    - {label: 'Unit Cost', property: costPerBird}
                    - {label: 'Ducks', property: totalDucks}
                    - {label: 'Total Cost', property: totalAcquireCost}
            form:
                fields: 
                    - 'name'
                    - 'category'
                    - {property: 'dateAcquired', type: 'date'}
                    - 'numberOfMales'
                    - 'numberOfFemales'
                    - 'costPerBird'
                    - 'supplier'
                    - 'farm'
                    - 'sellingprice'
            edit:
                title: update batch details
        Expense:
            class: 'App\Entity\Expense'
            form:
                title: 'Add New Expense'
                fields:
                    - {name: date, type: date, property: date}
                    - description
                    - amount
                    - category
                    - batch
            edit:
                title: 'Update Expense'
        Income:
            class: 'App\Entity\Income'
        Farm:
            class: 'App\Entity\Farm'
            controller: App\Controller\FarmEAController
            form:
                title: 'New Farm'
                fields:
                    - { property: name }
                    - { property: location }
            edit:
                title: 'Update Farm'
                fields:
                    - { property: name }
                    - { property: location }
                    - { property: owner }
            list:
                title: 'Your Farms'
                fields:
                    - { property: name }
                    - { property: location }
                    - { property: batch.count }
        Appuser:
            title: User
            class: 'App\Entity\Appuser'
            controller: App\Controller\AppuserController
            form:
                title: 'Add User'
                fields: 
                    - 'email'
                    - { property: 'password', type: 'password' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_ADMIN': 'ROLE_ADMIN','ROLE_USER': 'ROLE_USER'  } } }
            list:
                fields:
                    - { property: email }
                    - { property: password }
        Category:
            class: 'App\Entity\Category'
            new:
                fields: ['name']