easy_admin:
    design:
        brand_color: gold
    site_name: Pato
    entities:
        Batch:
            class: 'App\Entity\Batch'
            list:
                fields:
                    - name
                    - dateAcquired
                    - costPerBird
            new:
                fields: 
                    - 'name'
                    - 'type'
                    - 'dateAcquired'
                    - 'numberOfMales'
                    - 'numberOfFemales'
                    - 'costPerBird'
                    - 'supplier'
        Type:
            class: 'App\Entity\Type'
        Expense:
            class: 'App\Entity\Expense'
            new:
                fields:
                    - {name: date, type: date, property: date}
                    - description
                    - amount
                    - type
                    - category
        Income:
            class: 'App\Entity\Income'
        Category:
            class: 'App\Entity\Category'
            new:
                fields: ['name']