easy_admin:
    design:
        brand_color: gold
        menu:
            - { label: 'Home', route: 'home_index'}
            - {label: 'Account', children: ['Expense', 'Income', 'Type']}
            - { entity: 'Batch', default: true }
            - 'Category'
            - 'Appuser'
    site_name: Farm Back End
    entities:
        Batch:
            class: 'App\Entity\Batch'
            list:
                fields:
                    - name
                    - dateAcquired
                    - {label: 'Unit Cost', property: costPerBird}
                    - {label: 'Ducks', property: totalDucks}
                    - {label: 'Total Cost', property: totalAcquireCost}
            new:
                fields: 
                    - 'name'
                    - 'category'
                    - {property: 'dateAcquired', type: 'date'}
                    - 'numberOfMales'
                    - 'numberOfFemales'
                    - 'costPerBird'
                    - 'supplier'
        Type:
            class: 'App\Entity\Type'
            form:
                title: 'Add Expense Type'
                fields: [name]
            edit:
                title: 'Edit Expense Type'
        Expense:
            class: 'App\Entity\Expense'
            form:
                title: 'Add New Expense'
                fields:
                    - {name: date, type: date, property: date}
                    - description
                    - amount
                    - type
                    - category
                    - batch
            edit:
                title: 'Update Expense'
        Income:
            class: 'App\Entity\Income'
        Appuser:
            title: User
            class: 'App\Entity\Appuser'
            controller: App\Controller\AppuserController
            form:
                title: 'Add User'
                fields: 
                    - 'email'
                    - { property: 'password', type: 'password' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_ADMIN': 'ROLE_ADMIN','ROLE_USER': 'ROLE_USER'  } } }
            list:
                fields:
                    - { property: email }
                    - { property: password }
        Category:
            class: 'App\Entity\Category'
            new:
                fields: ['name']