easy_admin:
    entities:
        Batch:
            class: 'App\Entity\Batch'
            list:
                fields:
                    - Name
            new:
                fields: ['name', 'type', 'dateAcquired', 'numberOfMales', 'numberOfFemales', 'costPerBird']
        Type:
            class: 'App\Entity\Type'